apiVersion: batch/v1
kind: Job
metadata:
  name: train-ml
spec:
  template:
    spec:
      containers:
      - name: train-ml
        imagePullPolicy: Always
        image: shaybstrong/train-sklearn:0.1
        command: ["python3",  "train.py"]
      restartPolicy: Never
  backoffLimit: 0
